services:
  webapp: 
    build: streamlit/ # build from a Dockerfile in HW3-Assigned folder
    platform: linux/amd64
    ports:  # the port mappings between the host machine and the container
      - "80:8501" # map host's port 80 to container's 8501
    env_file: #  specify one or more files that contain environment variables
      - .env 
    volumes: # specify a volume mount (VOLUME:CONTAINER_PATH), or an access mode (VOLUME:CONTAINER_PATH:ACCESS_MODE).
      - /Users/brandonminer/.ssh/data-aquisition-470421-ee01c59cca25.json:/tmp/gcp-key.json
  api-server:
    build: fastapi/ # build from a Dockerfile in ex01 folder
    platform: linux/amd64
    ports:
      - "8000:8000"
    networks:  #  Specify which networks the containers for that service should connect to/communicate with.
      - app-network
    env_file: #  specify one or more files that contain environment variables
      - .env 
    volumes:
      - /Users/brandonminer/.ssh/data-aquisition-470421-ee01c59cca25.json:/tmp/gcp-key.json
  cron:
    build: crontab/
    depends_on: # To control the order of service startup and shutdown.
      - api-server # depends on it
    networks:
      - app-network # name of the network
networks: # Networks let services communicate with each other
  # By default, services can all communicate.
  app-network: # In this case, we don't actually need extra network. 
